# This service is used to ask the speaker to list objects detected at a proper direction:
# The request consists in:
# detections: the detected objects with scores
# direction: an integer representing the direction at which the objects have been detected
# The response is True if the operation was successful, False otherwise.

pepper_msgs/DetectionWithScore[]            detections
int8                                        direction

---

bool                                        success