# This service is used to ask the robot to take a picture in a proper direction.
# The request consists in an integer representing the direction at which the picture is taken
# The response is True if the operation was successful, False otherwise

int8 direction

---

bool success
